---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: stomm/alpine-bash-ssh-git

inputs:
- name: git-ci
- name: git-service-instances

outputs:
- name: updated-instances-repo

params:
  os_image_id: UNSPECIFIED
  os_external_network_id: UNSPECIFIED
  os_dns_nameservers: UNSPECIFIED
  small_flavor: UNSPECIFIED
  medium_flavor: UNSPECIFIED
  external_ip_pool: UNSPECIFIED

run:
  path: bash
  args:
  - -exc
  - |
    echo "## Cloning instances repo"
    git clone git-service-instances updated-instances-repo
    echo "## Generating new SSH keys"
    ./git-ci/pipeline/scripts/generate-ssh-keys.sh updated-instances-repo
    echo "## Creating tfvars"
    ./git-ci/pipeline/scripts/create-tfvars.sh git-ci updated-instances-repo "$os_image_id" "$os_external_network_id" "$small_flavor" "$medium_flavor" "$external_ip_pool" "$os_dns_nameservers"
